== Plants
The system is in its Proof of concept stage. I planted many different vegies.
The 3 most important ones being:

* tomatoes
* cucumber
* radish

Not planted but in the pipe are:

* strawberries
* tobacco
* blueberries
* some kind of pumpkins - e.g.: Cucurbita pepo

...to be extended ...

== Fish
Due to its resistance to harsh conditions, ease of keeping, uncomplicated diet the system operates on Brown Bullheads.
Ameiurus nebulosus (Lesueur, 1819).
Brown bullheads are also delicious and are supposed to grow relatively fast. (we will see that quite soon, won't we...)
Preparing Brown bullheads is an easy task once you mind the spikes hiden in 3 of their fins. Chaingloves should be used
whenever touching the animals. Also mind transporting them in tanks with not sufficient space as they might become
aggressive thus piercing eachother.

...to be extended...

== Computer setup

We are using a RaspberryPi. For further details refer to the RaspberryPi documentation.

== External hardware controll
To read more on this topic, refer to the documentation: *_RaspberryControlling_*
There are as of now 8 relay switches on relay board nr.1:

//[cols="0m, m, 0m, 0m, 0m, 0m, 0m", grid=none, frame=none, options="header"]
[]
|===
|nr.|device             |in/ont |via            |circuit|controlled |pos.
| 1.|light-1            |out    |socket_a       |230V   |pin-14     |8
| 2.|feeding wheel      |out    |socket_b       |230V   |pin-15     |10
| 3.|air circulation    |out    |socket_c       |230V   |pin-18     |12
| 4.|circulation pump   |out    |socket_d       |230V   |pin-7      |26
| 5.|light-2            |out    |socket_e       |230V   |pin-12     |32
| 6.|ventillation       |out    |socket-f       |230V   |pin-16     |36
| 7.|shade - lower      |out    |switch_Aa      |230V   |pin-20     |38
| 8.|shade - raise      |out    |switch_Ab      |230V   |pin-21     |40
|===

There are as of now 2 relay switches on relay board nr.2:

//[cols="0m, m, 0m, 0m, 0m, 0m, 0m", grid=none, frame=none, options="header"]
[]
|===
|nr.|device             |in/out |via            |circuit|controlled |pos.
| 1.|led                |out    |switch_B       |12V    |pin-17     |11
| 2.|sensor waterlevel  |in     |switch_C       |5V     |pin-27     |13
| 3.|sensor temperature |in     |switch_D       |5V     |           |
|===

== Install
once finished regular install:

=== Manual install-steps
Work you way through the following list manually:

* *keyboard*: to appropriate language - `MainMenu/Preferences/Raspberry Pi Configuration - Localisation`
* *ip* settings: fixed ip based on Local Area Network - for fixed IP, see Linux manual
** if possible, use LAN connection as it is always more relible, less proun to interference.
* (possible settings on LAN server - disable DHCP)
* enable *interfaces*: ssh, vlc, camera - `MainMenu/Preferences/Raspberry Pi Configuration - Interfaces`
* *sense hat* - install: (if not available from the box)

 sudo apt-get install sense-hat

=== Automated install-steps
THe following steps can either be taken manually or use the custom-made script found at: <<shell:scripts>>


* display sharing: using *xrdp*
** Automated install: <<shell:xrdp>>
** Manual install:

 sudo apt-get install xrdp

* mounting remote directories: using *cifs*
** Automated install: <<shell:cifs>>
** Manual install:

 sudo apt install net-tools
 sudo apt-get install cifs-utils

* to mount:

 sudo mount.cifs //10.3.77.x/h/Film /mnt/film/ -o user=pi,password=apuci

* enable file sharing: using *samba*
** Automated install: <<shell:samba>>
** Manual install:

